spring:
  application:
    name: visualizer-library-client
  profiles:
    active: resilience4j
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

use: feign

