spring:
  messages:
    baseName: i18n/appmessages
    encoding: UTF-8
    fallbackToSystemLocale: false
test:
  rightAnswersCountToPass: 3
  locale: ru-RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv